### ISSUE TITLE
Bad Current value

### ISSUE THREAD

**Issue by danielemereu** [corneliu-serediuc/Xamarin.Forms.KnobControl#1]
Hi, your knob implementation is very useful.
I've a problem when I try to read the "Current" value from the "KnobControl.cs". The value returned is always the first that you've set when create the object (in your example, for the first knob, it's always 25) even after the rotation of the knob.
Is it possibly a problem of "BindableProperty" inside the Knob class?

Thank you very much in advance
[KnobControl.txt](https://github.com/corneliu-serediuc/Xamarin.Forms.KnobControl/files/50725/KnobControl.txt)

.

**Comment by corneliu-serediuc** [comment]
Hi @danielemereu,

I have fixed the issue. Let me know if it works and if I can close this.
Thank you for reporting it.

BR // Corneliu

**Comment by danielemereu** [comment]
Hi @corneliu-serediuc 
yes the issue has been fixed. You can change also the Android version of KnobRenderer.cs in the same way if you want.
Thanks a lot
Daniele
